apiVersion: v1
kind: Service
metadata:
    name: gitrank-kafka
    labels:
      name: kafka
spec:
    ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
    selector:
      app: kafka
      id: "0"
    type: LoadBalancer
